// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfgiwoupyrueeqsnfosa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZ2l3b3VweXJ1ZWVxc25mb3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwODY4MzAsImV4cCI6MjA4NjY2MjgzMH0.we3N6noqOrRGgE0_vbFrcu5ZJm2Hxk5LCf20pBRNYyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});